name: Rust extension

on:
  push:
    branches:
      - main
  pull_request: {}
  workflow_dispatch: {}

env:
  EMSCRIPTEN_VERSION: "3.1.45"

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11.4

      - uses: mymindstorm/setup-emsdk@v12
        with:
          version: ${{ env.EMSCRIPTEN_VERSION }}

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          target: wasm32-unknown-emscripten

      - name: Install pyodide-build
        run: |
          pip install maturin pyodide-build

      - name: Build wasm wheel
        run: |
          maturin build --release -o dist --target wasm32-unknown-emscripten -i python3.11
        working-directory: ./rust-extension

      - name: Install and test
        working-directory: ./rust-extension
        run: |
          pyodide venv .venv-pyodide
          source .venv-pyodide/bin/activate
          pip install dist/*.whl
          python ./test.py

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./rust-extension/dist

  deploy:
    needs: test
    if: github.ref == 'refs/heads/main'
    permissions:
      pages: write
      id-token: write

    environment:
      name: rust-wasm-wheel
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
